### ISSUE TITLE
Не получается присоединиться к сообществу

### ISSUE THREAD

**Issue by mephistorine** [be-Cycled/beCycled-frontend#21]
Илья сделал новые эндпоинты

**Comment by I1yi4** [comment]
/communities/join/{id} - присоединиться к сообществу с {id} 
/communities/leave/{id} - покинуть сообщество с {id}

**Comment by binakot** [comment]
Почему я до сих пор не могу присоединится к Waliot Sport Team!
Срочно сделайте мне эту функцию 💢

**Comment by mephistorine** [comment]
ждите
