### ISSUE TITLE
Добавить кнопки НАЗАД в событии и карточке сообщества

### ISSUE THREAD

**Issue by avkoltovich** [be-Cycled/beCycled-frontend#31]
Нужно добавить кнопки назад, как это реализовано в cycled

**Comment by mephistorine** [comment]
А кнопкной назад в браузере не получится?

**Comment by avkoltovich** [comment]
> А кнопкной назад в браузере не получится?

В предыдущей реализации cycled у меня просили эту кнопку. Было удобно.

**Comment by mephistorine** [comment]
Думаю это будет иметь больше смысла для мобильной версии, особенно для PWA

**Comment by binakot** [comment]
Плюсую! Сильно горит с мобилки, когда не можешь вернуться назад. Тут надо ли продумывать навигацию в рамках разделе через вкладки и ржаные сухарики (ака хлебные крошки), чтобы не было вообще необходимости идти назад, либо все-таки сделать эту кнопку.
