### ISSUE TITLE
Развернутая страница участников сообщества

### ISSUE THREAD

**Issue by mephistorine** [be-Cycled/beCycled-frontend#39]
### Описание

На данный момент не предусмотрен UI, для большого количества участников. Так что нужно сделать отдельную страницу для развернутого списка участников.

![Примерный дизайн развернутого списка участников](https://user-images.githubusercontent.com/17084223/123590753-bd6d1700-d7f3-11eb-9527-ca8eab6b4cc6.png)

Рядом с заголовком "Участники" появится количество участников, которые не поместились в мини-превью. По клику на заголовок будет открываться развернутый список участников.

**Comment by binakot** [comment]
Текущее положение дел 😄 

![Снимок экрана 2021-07-06 в 13 35 25](https://user-images.githubusercontent.com/1783893/124586770-8a63fc80-de5f-11eb-9a46-92c0fb4e95c6.png)
