### ISSUE TITLE
Добавить галочку соглашения о персональный данных при регистрации

### ISSUE THREAD

**Issue by binakot** [be-Cycled/beCycled-frontend#48]
### Описание

Нужно соблюдать 152-ФЗ http://www.consultant.ru/document/cons_doc_LAW_61801.
При регистрации пользователь ОБЯЗАН поставить галочку, что он согласен передать нам свои ПД.
Вот тут можно почитать, что нужно сделать https://www.extyl-pro.ru/library/elektronnaya-torgovlya/152-fz-i-personalnye-dannye-kakie-galochki-postavit-chtoby-ne-poluchit-300-000-shtrafa/

### Решение

Добавить пункт при регистрации с галочкой и ссылкой на соглашении о ПД. Ее текст типовой, можно скопировать шаблон и подставить свои наименования.

**Comment by mephistorine** [comment]
@binakot ты можешь подготовить готовую PDF с соглашением?

**Comment by binakot** [comment]
[beCycled - Пользовательское соглашение.pdf](https://github.com/be-Cycled/beCycled-frontend/files/6892342/beCycled.-.pdf)

[beCycled - Политика конфиденциальности.pdf](https://github.com/be-Cycled/beCycled-frontend/files/6892452/beCycled.-.pdf)
