### ISSUE TITLE
Добавить футер с копирайтами, контактами и прочее

### ISSUE THREAD

**Issue by binakot** [be-Cycled/beCycled-frontend#51]
### Описание

Не хватает футера с копирайтами, контактами (support@becycled.me) и ссылки на github (можно обсудить, нужна ли она на сайте)

### Решение

Очевидно, добавить футер :)

**Comment by mephistorine** [comment]
Так же можно добавить ссылки на соц. сети
- Телеграм: https://t.me/beCycled
- VK: https://vk.com/becycled
- Instagram: https://www.instagram.com/becycled.me/
- Twitter: В процессе...

**Comment by binakot** [comment]
> Так же можно добавить ссылки на соц. сети
> 
> * Телеграм: https://t.me/beCycled
> * VK: https://vk.com/becycled
> * Instagram: https://www.instagram.com/becycled.me/
> * Twitter: В процессе...

И фейсбук!

**Comment by binakot** [comment]
Я дал @avkoltovich доступ ко всем почтовым ящикам. Через них он сможет везде завести аккаунты.

**Comment by binakot** [comment]
Не забыть про партнеров :)

**Comment by binakot** [comment]
[beCycled - Пользовательское соглашение.pdf](https://github.com/be-Cycled/beCycled-frontend/files/6892340/beCycled.-.pdf)

[beCycled - Политика конфиденциальности.pdf](https://github.com/be-Cycled/beCycled-frontend/files/6892449/beCycled.-.pdf)
