### ISSUE TITLE
Перевести картинки с base64 на файлы

### ISSUE THREAD

**Issue by avkoltovich** [be-Cycled/beCycled-frontend#67]
### Описание

Теперь есть возможность аплоадить изображения на бэк и получать в результате полноценную ссылку на картинку.

Нужно переписать все места использования этих картинок на прямые ссылки.

### Решение

Предварительно нужно мигрировать базу на новый формат изображений.

**Comment by binakot** [comment]
Здесь полезные ссылки из задачи по бэку https://github.com/be-Cycled/beCycled-backend/issues/22
Там есть примеры с Angular
